server:
  port: 8081

spring:
  datasource:
        url: jdbc:mysql://172.17.0.2:3306/isda
        username: root
        password: rootpass
        driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ducnmpad@gmail.com
    password: hbuxbkrxzqamqxya
    properties:
        mail:
            smtp:
            auth: true
            starttls:
                enable: true